# Generated by Django 6.0.6 on 2026-06-05 13:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('brand', 0), ('title', 1), ('description', 2), ('highlight', 3), ('highlight_part2', 4)]], {})}),
        ),
    ]
