# Generated by Django 6.0.6 on 2026-06-05 13:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('about', 8), ('vision', 14), ('services', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('brand', 0), ('title', 1), ('description', 2), ('highlight', 3), ('highlight_part2', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'من نحن', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'default': 'تأسست شركة برايم شيلد لتكون المحـور الأساسي الذي يلتقــي فيــــــــه الابتكــار الهندسي بالتميز الإنشائي...', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': True}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/vision_result.webp', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('image_path', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('slides', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/service-1_result.webp', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('title', 9), ('desc', 10), ('image_path', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('services', 17)]], {})}),
        ),
    ]
