# Generated by Django 6.0.6 on 2026-06-05 13:52

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('hero', 6)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('brand', 1), ('title', 2), ('description', 3), ('highlight', 4), ('highlight_part2', 5)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
