# Generated by Django 6.0.6 on 2026-06-17 12:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_standardpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 6), ('about', 9), ('vision', 15), ('services', 19)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for this hero section', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('brand', 1), ('title', 2), ('description', 3), ('highlight', 4), ('highlight_part2', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'من نحن', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'default': 'تأسست شركة برايم شيلد لتكون المحـور الأساسي الذي يلتقــي فيــــــــه الابتكــار الهندسي بالتميز الإنشائي...', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('description', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/vision_result.webp', 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('title', 10), ('text', 11), ('image_path', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('slides', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/service-1_result.webp', 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 10), ('desc', 11), ('image_path', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('services', 18)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('hero', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for this hero section', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('background_image', 1), ('brand', 2), ('title', 3), ('description', 4), ('highlight', 5), ('highlight_part2', 6)]], {})}),
        ),
    ]
