# Generated by Django 6.0.6 on 2026-06-20 18:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_civilianewsindexpage_civilianewspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('embed_html', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Embed HTML'})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('hero', 7), ('embed_html', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for this hero section', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'default': 'شركة سعوديــــة رائــدة متخصصــة في حلــول العزل المائي والحراري...', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'نجمـــــع بيـــــن خبـــــــــــرة تتجـــــاوز 40 عامًـــــــــــا', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'وأكثـــر مــن 12 عامًــا من التخصص الدقيــق في أنظمة العزل الهندسـي', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('background_image', 1), ('brand', 2), ('title', 3), ('description', 4), ('highlight', 5), ('highlight_part2', 6)]], {}), 8: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Embed HTML'})}),
        ),
    ]
