# Generated by Django 6.0.6 on 2026-06-20 18:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blogpage_body_alter_standardpage_body'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiviliaHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1_title', models.CharField(blank=True, help_text='Main H1 heading shown on the homepage', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines (150–160 characters recommended)')),
            ],
            options={
                'verbose_name': 'Civilia Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrimeShieldHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1_title', models.CharField(blank=True, help_text='Main H1 heading shown on the homepage', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines (150–160 characters recommended)')),
            ],
            options={
                'verbose_name': 'PrimeShield Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrimeShieldProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrimeShieldServicesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Services',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='civilianewsindexpage',
            options={'verbose_name': 'Civilia News'},
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Short excerpt shown on the blog listing (2–3 sentences).'),
        ),
        migrations.AlterField(
            model_name='civilianewspage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description shown on news listing cards.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('about', 7), ('vision', 13), ('services', 17)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('background_image', 0), ('brand', 1), ('title', 2), ('description', 3), ('highlight', 4), ('highlight_part2', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'من نحن', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 3)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'required': True}), 9: ('wagtail.blocks.TextBlock', (), {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/vision_result.webp', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 8), ('text', 9), ('image_path', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('slides', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. /assets/service-1_result.webp', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 8), ('desc', 9), ('image_path', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('services', 16)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('hero', 6), ('embed_html', 7)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'برايم شيلد |', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'خبرة هندسية في المقاولات العامة و خدمات العزل', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('background_image', 1), ('brand', 2), ('title', 3), ('description', 4), ('highlight', 5), ('highlight_part2', 5)]], {}), 7: ('wagtail.blocks.RawHTMLBlock', (), {'label': 'Embed HTML'})}),
        ),
        migrations.CreateModel(
            name='PrimeShieldProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, help_text='e.g. 5,000 sqm', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default='completed', max_length=20)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PrimeShieldServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
            bases=('wagtailcore.page',),
        ),
    ]
